"""Change tracker.id from int to str

Revision ID: 506187b4dc3e
Revises: 2a39b2cf0d9c
Create Date: 2025-08-10 14:24:35.369615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506187b4dc3e'
down_revision: Union[str, Sequence[str], None] = '2a39b2cf0d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('trackers', 'id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('trackers', 'id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)

def upgrade():
    with op.batch_alter_table("trackers", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.String(),
            existing_nullable=False
        )


def downgrade():
    with op.batch_alter_table("trackers", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(),
            type_=sa.Integer(),
            existing_nullable=False
        )
    # ### end Alembic commands ###
