"""default uuid for trackers is now generate_uuid() function

Revision ID: 7c4b2baf72b3
Revises: 506187b4dc3e
Create Date: 2025-08-10 14:53:21.325220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4b2baf72b3'
down_revision: Union[str, Sequence[str], None] = '506187b4dc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
